name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command_timeout: 30s
          script: |
            whoami
            pwd
            ls -la
            cd /var/www/kilowatt
            git config --global --add safe.directory /var/www/kilowatt
            git status
            git remote -v
            git fetch origin
            git reset --hard origin/main
            git pull origin main 