name: Deploy to Production

on:
  push:
    branches:
      - main  # или master, в зависимости от вашей основной ветки

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          command_timeout: 30s
          script: |
            whoami
            pwd
            ls -la
            cd /var/www/kilowatt
            git pull origin main 